# Autogenerated wrapper script for esbuild_jll for x86_64-w64-mingw32
export esbuild

JLLWrappers.@generate_wrapper_header("esbuild")
JLLWrappers.@declare_executable_product(esbuild)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        esbuild,
        "bin\\esbuild.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
